var searchData=
[
  ['ublas_5finterface',['ublas_interface',['../classublas__interface.html',1,'']]],
  ['umeyama_5ftransform_5fmatrix_5ftype',['umeyama_transform_matrix_type',['../struct_eigen_1_1internal_1_1umeyama__transform__matrix__type.html',1,'Eigen::internal']]],
  ['umfpack_5fhelper_5fis_5fsparse_5fplain',['umfpack_helper_is_sparse_plain',['../struct_eigen_1_1internal_1_1umfpack__helper__is__sparse__plain.html',1,'Eigen::internal']]],
  ['umfpack_5fhelper_5fis_5fsparse_5fplain_3c_20mappedsparsematrix_3c_20scalar_2c_20options_2c_20storageindex_20_3e_20_3e',['umfpack_helper_is_sparse_plain&lt; MappedSparseMatrix&lt; Scalar, Options, StorageIndex &gt; &gt;',['../struct_eigen_1_1internal_1_1umfpack__helper__is__sparse__plain_3_01_mapped_sparse_matrix_3_01_sccebbb637d4478d7636b2c08188e4de46.html',1,'Eigen::internal']]],
  ['umfpack_5fhelper_5fis_5fsparse_5fplain_3c_20sparsematrix_3c_20scalar_2c_20options_2c_20storageindex_20_3e_20_3e',['umfpack_helper_is_sparse_plain&lt; SparseMatrix&lt; Scalar, Options, StorageIndex &gt; &gt;',['../struct_eigen_1_1internal_1_1umfpack__helper__is__sparse__plain_3_01_sparse_matrix_3_01_scalar_006a4d34a0152a72ef68223c72b8a2e388.html',1,'Eigen::internal']]],
  ['umfpacklu',['UmfPackLU',['../class_eigen_1_1_umf_pack_l_u.html',1,'Eigen']]],
  ['unaligned_5fassign_5fimpl',['unaligned_assign_impl',['../struct_eigen_1_1internal_1_1unaligned__assign__impl.html',1,'Eigen::internal']]],
  ['unaligned_5fassign_5fimpl_3c_20false_20_3e',['unaligned_assign_impl&lt; false &gt;',['../struct_eigen_1_1internal_1_1unaligned__assign__impl_3_01false_01_4.html',1,'Eigen::internal']]],
  ['unary_5fresult_5fof_5fselect',['unary_result_of_select',['../struct_eigen_1_1internal_1_1unary__result__of__select.html',1,'Eigen::internal']]],
  ['unary_5fresult_5fof_5fselect_3c_20func_2c_20argtype_2c_20sizeof_28has_5fstd_5fresult_5ftype_29_3e',['unary_result_of_select&lt; Func, ArgType, sizeof(has_std_result_type)&gt;',['../struct_eigen_1_1internal_1_1unary__result__of__select_3_01_func_00_01_arg_type_00_01sizeof_07has__std__result__type_08_4.html',1,'Eigen::internal']]],
  ['unary_5fresult_5fof_5fselect_3c_20func_2c_20argtype_2c_20sizeof_28has_5ftr1_5fresult_29_3e',['unary_result_of_select&lt; Func, ArgType, sizeof(has_tr1_result)&gt;',['../struct_eigen_1_1internal_1_1unary__result__of__select_3_01_func_00_01_arg_type_00_01sizeof_07has__tr1__result_08_4.html',1,'Eigen::internal']]],
  ['uniformscaling',['UniformScaling',['../class_eigen_1_1_uniform_scaling.html',1,'Eigen']]],
  ['unitorthogonal_5fselector',['unitOrthogonal_selector',['../struct_eigen_1_1internal_1_1unit_orthogonal__selector.html',1,'Eigen::internal']]],
  ['unitorthogonal_5fselector_3c_20derived_2c_202_20_3e',['unitOrthogonal_selector&lt; Derived, 2 &gt;',['../struct_eigen_1_1internal_1_1unit_orthogonal__selector_3_01_derived_00_012_01_4.html',1,'Eigen::internal']]],
  ['unitorthogonal_5fselector_3c_20derived_2c_203_20_3e',['unitOrthogonal_selector&lt; Derived, 3 &gt;',['../struct_eigen_1_1internal_1_1unit_orthogonal__selector_3_01_derived_00_013_01_4.html',1,'Eigen::internal']]],
  ['unpacket_5ftraits',['unpacket_traits',['../struct_eigen_1_1internal_1_1unpacket__traits.html',1,'Eigen::internal']]],
  ['unpacket_5ftraits_3c_20packet1cd_20_3e',['unpacket_traits&lt; Packet1cd &gt;',['../struct_eigen_1_1internal_1_1unpacket__traits_3_01_packet1cd_01_4.html',1,'Eigen::internal']]],
  ['unpacket_5ftraits_3c_20packet2cf_20_3e',['unpacket_traits&lt; Packet2cf &gt;',['../struct_eigen_1_1internal_1_1unpacket__traits_3_01_packet2cf_01_4.html',1,'Eigen::internal']]],
  ['unpacket_5ftraits_3c_20packet2d_20_3e',['unpacket_traits&lt; Packet2d &gt;',['../struct_eigen_1_1internal_1_1unpacket__traits_3_01_packet2d_01_4.html',1,'Eigen::internal']]],
  ['unpacket_5ftraits_3c_20packet4f_20_3e',['unpacket_traits&lt; Packet4f &gt;',['../struct_eigen_1_1internal_1_1unpacket__traits_3_01_packet4f_01_4.html',1,'Eigen::internal']]],
  ['unpacket_5ftraits_3c_20packet4i_20_3e',['unpacket_traits&lt; Packet4i &gt;',['../struct_eigen_1_1internal_1_1unpacket__traits_3_01_packet4i_01_4.html',1,'Eigen::internal']]],
  ['unusable',['Unusable',['../class_eigen_1_1_return_by_value_1_1_unusable.html',1,'Eigen::ReturnByValue']]],
  ['upperbidiagonalization',['UpperBidiagonalization',['../class_eigen_1_1internal_1_1_upper_bidiagonalization.html',1,'Eigen::internal']]]
];
