var searchData=
[
  ['make_5fcoherent_5fimpl',['make_coherent_impl',['../struct_eigen_1_1internal_1_1make__coherent__impl.html',1,'Eigen::internal']]],
  ['make_5fcoherent_5fimpl_3c_20a_2c_20matrix_3c_20b_5fscalar_2c_20b_5frows_2c_20b_5fcols_2c_20b_5foptions_2c_20b_5fmaxrows_2c_20b_5fmaxcols_20_3e_20_3e',['make_coherent_impl&lt; A, Matrix&lt; B_Scalar, B_Rows, B_Cols, B_Options, B_MaxRows, B_MaxCols &gt; &gt;',['../struct_eigen_1_1internal_1_1make__coherent__impl_3_01_a_00_01_matrix_3_01_b___scalar_00_01_b___r2332686f3180c2f2d848d1b5e8319450.html',1,'Eigen::internal']]],
  ['make_5fcoherent_5fimpl_3c_20matrix_3c_20a_5fscalar_2c_20a_5frows_2c_20a_5fcols_2c_20a_5foptions_2c_20a_5fmaxrows_2c_20a_5fmaxcols_20_3e_2c_20b_20_3e',['make_coherent_impl&lt; Matrix&lt; A_Scalar, A_Rows, A_Cols, A_Options, A_MaxRows, A_MaxCols &gt;, B &gt;',['../struct_eigen_1_1internal_1_1make__coherent__impl_3_01_matrix_3_01_a___scalar_00_01_a___rows_00_0aa8f55819fa60ac5751cc2cbbaa58000.html',1,'Eigen::internal']]],
  ['make_5fcoherent_5fimpl_3c_20matrix_3c_20a_5fscalar_2c_20a_5frows_2c_20a_5fcols_2c_20a_5foptions_2c_20a_5fmaxrows_2c_20a_5fmaxcols_20_3e_2c_20matrix_3c_20b_5fscalar_2c_20b_5frows_2c_20b_5fcols_2c_20b_5foptions_2c_20b_5fmaxrows_2c_20b_5fmaxcols_20_3e_20_3e',['make_coherent_impl&lt; Matrix&lt; A_Scalar, A_Rows, A_Cols, A_Options, A_MaxRows, A_MaxCols &gt;, Matrix&lt; B_Scalar, B_Rows, B_Cols, B_Options, B_MaxRows, B_MaxCols &gt; &gt;',['../struct_eigen_1_1internal_1_1make__coherent__impl_3_01_matrix_3_01_a___scalar_00_01_a___rows_00_02c107ffcc218caac688e11f3e382ff61.html',1,'Eigen::internal']]],
  ['make_5fproper_5fmatrix_5ftype',['make_proper_matrix_type',['../class_eigen_1_1internal_1_1make__proper__matrix__type.html',1,'Eigen::internal']]],
  ['makecomplexop',['MakeComplexOp',['../struct_make_complex_op.html',1,'']]],
  ['mandelbrotthread',['MandelbrotThread',['../class_mandelbrot_thread.html',1,'']]],
  ['mandelbrotwidget',['MandelbrotWidget',['../class_mandelbrot_widget.html',1,'']]],
  ['map',['Map',['../class_eigen_1_1_map.html',1,'Eigen']]],
  ['map_3c_20const_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e',['Map&lt; const Quaternion&lt; _Scalar &gt;, _Options &gt;',['../class_eigen_1_1_map_3_01const_01_quaternion_3_01___scalar_01_4_00_01___options_01_4.html',1,'Eigen']]],
  ['map_3c_20matrix_3c_20scalar_2c_20dynamic_2c_20dynamic_2c_20colmajor_20_3e_2c_200_2c_20outerstride_3c_3e_20_3e',['Map&lt; Matrix&lt; Scalar, Dynamic, Dynamic, ColMajor &gt;, 0, OuterStride&lt;&gt; &gt;',['../class_eigen_1_1_map.html',1,'Eigen']]],
  ['map_3c_20permutationmatrix_3c_20sizeatcompiletime_2c_20maxsizeatcompiletime_2c_20indextype_20_3e_2c_20_5fpacketaccess_20_3e',['Map&lt; PermutationMatrix&lt; SizeAtCompileTime, MaxSizeAtCompileTime, IndexType &gt;, _PacketAccess &gt;',['../class_eigen_1_1_map_3_01_permutation_matrix_3_01_size_at_compile_time_00_01_max_size_at_compile_f743474e57c9138756df68cf650ef435.html',1,'Eigen']]],
  ['map_3c_20quaternion_3c_20_5fscalar_20_3e_2c_20_5foptions_20_3e',['Map&lt; Quaternion&lt; _Scalar &gt;, _Options &gt;',['../class_eigen_1_1_map_3_01_quaternion_3_01___scalar_01_4_00_01___options_01_4.html',1,'Eigen']]],
  ['map_3c_20transpositions_3c_20sizeatcompiletime_2c_20maxsizeatcompiletime_2c_20indextype_20_3e_2c_20packetaccess_20_3e',['Map&lt; Transpositions&lt; SizeAtCompileTime, MaxSizeAtCompileTime, IndexType &gt;, PacketAccess &gt;',['../class_eigen_1_1_map_3_01_transpositions_3_01_size_at_compile_time_00_01_max_size_at_compile_time495b7bd1eee539551679afbe5b4dd28d.html',1,'Eigen']]],
  ['map_5fsize',['map_size',['../structmap__size.html',1,'']]],
  ['map_5fsize_3c_2010_20_3e',['map_size&lt; 10 &gt;',['../structmap__size_3_0110_01_4.html',1,'']]],
  ['map_5fsize_3c_2011_20_3e',['map_size&lt; 11 &gt;',['../structmap__size_3_0111_01_4.html',1,'']]],
  ['map_5fsize_3c_2012_20_3e',['map_size&lt; 12 &gt;',['../structmap__size_3_0112_01_4.html',1,'']]],
  ['map_5fsize_3c_2013_20_3e',['map_size&lt; 13 &gt;',['../structmap__size_3_0113_01_4.html',1,'']]],
  ['mapbase',['MapBase',['../class_eigen_1_1_map_base.html',1,'Eigen']]],
  ['mapbase_3c_20block_3c_20xprtype_2c_20blockrows_2c_20blockcols_2c_20innerpanel_20_3e_20_3e',['MapBase&lt; Block&lt; XprType, BlockRows, BlockCols, InnerPanel &gt; &gt;',['../class_eigen_1_1_map_base.html',1,'Eigen']]],
  ['mapbase_3c_20derived_20_3e',['MapBase&lt; Derived &gt;',['../class_eigen_1_1_map_base.html',1,'Eigen']]],
  ['mapbase_3c_20derived_2c_20readonlyaccessors_20_3e',['MapBase&lt; Derived, ReadOnlyAccessors &gt;',['../class_eigen_1_1_map_base_3_01_derived_00_01_read_only_accessors_01_4.html',1,'Eigen']]],
  ['mapbase_3c_20derived_2c_20writeaccessors_20_3e',['MapBase&lt; Derived, WriteAccessors &gt;',['../class_eigen_1_1_map_base_3_01_derived_00_01_write_accessors_01_4.html',1,'Eigen']]],
  ['mapbase_3c_20map_3c_20plainobjecttype_2c_20mapoptions_2c_20stridetype_20_3e_20_3e',['MapBase&lt; Map&lt; PlainObjectType, MapOptions, StrideType &gt; &gt;',['../class_eigen_1_1_map_base.html',1,'Eigen']]],
  ['mapbase_3c_20ref_3c_20const_20tplainobjecttype_2c_20options_2c_20stridetype_20_3e_20_3e',['MapBase&lt; Ref&lt; const TPlainObjectType, Options, StrideType &gt; &gt;',['../class_eigen_1_1_map_base.html',1,'Eigen']]],
  ['mapbase_3c_20ref_3c_20plainobjecttype_2c_20options_2c_20stridetype_20_3e_20_3e',['MapBase&lt; Ref&lt; PlainObjectType, Options, StrideType &gt; &gt;',['../class_eigen_1_1_map_base.html',1,'Eigen']]],
  ['mappedskylinematrix',['MappedSkylineMatrix',['../class_eigen_1_1_mapped_skyline_matrix.html',1,'Eigen']]],
  ['mappedsparsematrix',['MappedSparseMatrix',['../class_eigen_1_1_mapped_sparse_matrix.html',1,'Eigen']]],
  ['mappedsparsematrix_3c_20scalar_2c_20colmajor_2c_20index_20_3e',['MappedSparseMatrix&lt; Scalar, ColMajor, Index &gt;',['../class_eigen_1_1_mapped_sparse_matrix.html',1,'Eigen']]],
  ['mappedsupernodalmatrix',['MappedSuperNodalMatrix',['../class_eigen_1_1internal_1_1_mapped_super_nodal_matrix.html',1,'Eigen::internal']]],
  ['mappedsupernodalmatrix_3c_20scalar_2c_20index_20_3e',['MappedSuperNodalMatrix&lt; Scalar, Index &gt;',['../class_eigen_1_1internal_1_1_mapped_super_nodal_matrix.html',1,'Eigen::internal']]],
  ['mapstaticmethods_5fimpl',['mapstaticmethods_impl',['../structmapstaticmethods__impl.html',1,'']]],
  ['mapstaticmethods_5fimpl_3c_20plainobjecttype_2c_20false_2c_20isvector_20_3e',['mapstaticmethods_impl&lt; PlainObjectType, false, IsVector &gt;',['../structmapstaticmethods__impl_3_01_plain_object_type_00_01false_00_01_is_vector_01_4.html',1,'']]],
  ['mapstaticmethods_5fimpl_3c_20plainobjecttype_2c_20true_2c_20false_20_3e',['mapstaticmethods_impl&lt; PlainObjectType, true, false &gt;',['../structmapstaticmethods__impl_3_01_plain_object_type_00_01true_00_01false_01_4.html',1,'']]],
  ['mapstaticmethods_5fimpl_3c_20plainobjecttype_2c_20true_2c_20true_20_3e',['mapstaticmethods_impl&lt; PlainObjectType, true, true &gt;',['../structmapstaticmethods__impl_3_01_plain_object_type_00_01true_00_01true_01_4.html',1,'']]],
  ['match',['match',['../struct_eigen_1_1internal_1_1traits_3_01_ref_3_01___plain_object_type_00_01___options_00_01___stride_type_01_4_01_4_1_1match.html',1,'Eigen::internal::traits&lt; Ref&lt; _PlainObjectType, _Options, _StrideType &gt; &gt;']]],
  ['matrix',['Matrix',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20complexscalar_2c_20colsatcompiletime_2c_201_2c_20options_20_26_28_7erowmajor_29_2c_20maxcolsatcompiletime_2c_201_20_3e',['Matrix&lt; ComplexScalar, ColsAtCompileTime, 1, Options &amp;(~RowMajor), MaxColsAtCompileTime, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20complexscalar_2c_20colsatcompiletime_2c_201_2c_20options_20_26_7erowmajor_2c_20maxcolsatcompiletime_2c_201_20_3e',['Matrix&lt; ComplexScalar, ColsAtCompileTime, 1, Options &amp;~RowMajor, MaxColsAtCompileTime, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20complexscalar_2c_20rowsatcompiletime_2c_20colsatcompiletime_2c_20eigen_3a_3amap_3a_3aoptions_2c_20maxrowsatcompiletime_2c_20maxcolsatcompiletime_20_3e',['Matrix&lt; ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Eigen::Map::Options, MaxRowsAtCompileTime, MaxColsAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20complexscalar_2c_20rowsatcompiletime_2c_20colsatcompiletime_2c_20matrixtype_3a_3aoptions_2c_20maxrowsatcompiletime_2c_20maxcolsatcompiletime_20_3e',['Matrix&lt; ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, MatrixType::Options, MaxRowsAtCompileTime, MaxColsAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20complexscalar_2c_20rowsatcompiletime_2c_20colsatcompiletime_2c_20options_2c_20maxrowsatcompiletime_2c_20maxcolsatcompiletime_20_3e',['Matrix&lt; ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20double_2c_203_2c_204_20_3e',['Matrix&lt; double, 3, 4 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20double_2c_20dparm_5fsize_2c_201_20_3e',['Matrix&lt; double, DPARM_SIZE, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20float_2c_202_2c_202_2c_20dontalign_20_3e',['Matrix&lt; float, 2, 2, DontAlign &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20float_2c_202_2c_206_20_3e',['Matrix&lt; float, 2, 6 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20index_2c_201_2c_20eigen_5fsize_5fmin_5fprefer_5fdynamic_28colsatcompiletime_2c_20rowsatcompiletime_29_2c_20rowmajor_2c_201_2c_20eigen_5fsize_5fmin_5fprefer_5ffixed_28maxcolsatcompiletime_2c_20maxrowsatcompiletime_29_3e',['Matrix&lt; Index, 1, EIGEN_SIZE_MIN_PREFER_DYNAMIC(ColsAtCompileTime, RowsAtCompileTime), RowMajor, 1, EIGEN_SIZE_MIN_PREFER_FIXED(MaxColsAtCompileTime, MaxRowsAtCompileTime)&gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20index_2c_20dynamic_2c_201_20_3e',['Matrix&lt; Index, Dynamic, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20index_2c_20matrixtype_3a_3arowsatcompiletime_2c_201_20_3e',['Matrix&lt; Index, MatrixType::RowsAtCompileTime, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20index_2c_20traits_3a_3arowsatcompiletime_2c_201_20_3e',['Matrix&lt; Index, Traits::RowsAtCompileTime, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20int_2c_201_2c_20matrixtype_3a_3acolsatcompiletime_20_3e',['Matrix&lt; int, 1, MatrixType::ColsAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20int_2c_20iparm_5fsize_2c_201_20_3e',['Matrix&lt; int, IPARM_SIZE, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20int_2c_20matrixtype_3a_3arowsatcompiletime_2c_201_20_3e',['Matrix&lt; int, MatrixType::RowsAtCompileTime, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20internal_3a_3ascalar_5fproduct_5ftraits_3c_20lhs_3a_3ascalar_2c_20rhs_3a_3ascalar_20_3e_3a_3areturntype_2c_201_2c_201_20_3e',['Matrix&lt; internal::scalar_product_traits&lt; Lhs::Scalar, Rhs::Scalar &gt;::ReturnType, 1, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20realscalar_2c_20dynamic_2c_201_20_3e',['Matrix&lt; RealScalar, Dynamic, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20realscalar_2c_20dynamic_2c_20dynamic_20_3e',['Matrix&lt; RealScalar, Dynamic, Dynamic &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20roottype_2c_20_5fdeg_2c_201_20_3e',['Matrix&lt; RootType, _Deg, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_201_2c_20rowsatcompiletime_2c_20rowmajor_2c_201_2c_20maxrowsatcompiletime_20_3e',['Matrix&lt; Scalar, 1, RowsAtCompileTime, RowMajor, 1, MaxRowsAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_201_2c_20size_2c_20options_7crowmajor_2c_201_2c_20maxsize_20_3e',['Matrix&lt; Scalar, 1, Size, Options|RowMajor, 1, MaxSize &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_203_2c_201_20_3e',['Matrix&lt; Scalar, 3, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_204_2c_201_20_3e',['Matrix&lt; Scalar, 4, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20ambientdimatcompiletime_2c_201_20_3e',['Matrix&lt; Scalar, AmbientDimAtCompileTime, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20colsatcompiletime_2c_201_2c_20options_20_26_7erowmajor_2c_20maxcolsatcompiletime_2c_201_20_3e',['Matrix&lt; Scalar, ColsAtCompileTime, 1, Options &amp;~RowMajor, MaxColsAtCompileTime, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20colsatcompiletime_2c_20colsatcompiletime_2c_20matrixoptions_2c_20maxcolsatcompiletime_2c_20maxcolsatcompiletime_20_3e',['Matrix&lt; Scalar, ColsAtCompileTime, ColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MaxColsAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20colsatcompiletime_2c_20rowsatcompiletime_2c_20options_2c_20maxcolsatcompiletime_2c_20maxrowsatcompiletime_20_3e',['Matrix&lt; Scalar, ColsAtCompileTime, RowsAtCompileTime, Options, MaxColsAtCompileTime, MaxRowsAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20deg_2c_201_20_3e',['Matrix&lt; Scalar, Deg, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20deg_5f1_2c_201_20_3e',['Matrix&lt; Scalar, Deg_1, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20diagsizeatcompiletime_2c_20diagsizeatcompiletime_2c_20matrixoptions_2c_20maxdiagsizeatcompiletime_2c_20maxdiagsizeatcompiletime_20_3e',['Matrix&lt; Scalar, DiagSizeAtCompileTime, DiagSizeAtCompileTime, MatrixOptions, MaxDiagSizeAtCompileTime, MaxDiagSizeAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20dim_2c_201_20_3e',['Matrix&lt; Scalar, Dim, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20dynamic_2c_201_20_3e',['Matrix&lt; Scalar, Dynamic, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20dynamic_2c_20dynamic_20_3e',['Matrix&lt; Scalar, Dynamic, Dynamic &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20eigen_3a_3adynamic_2c_201_20_3e',['Matrix&lt; Scalar, Eigen::Dynamic, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20hdim_2c_20hdim_20_3e',['Matrix&lt; Scalar, HDim, HDim &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20int_28ambientdimatcompiletime_29_3d_3ddynamic_3fdynamic_3aint_28ambientdimatcompiletime_29_2b1_2c_201_20_3e',['Matrix&lt; Scalar, int(AmbientDimAtCompileTime)==Dynamic?Dynamic:int(AmbientDimAtCompileTime)+1, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20matrixtype_3a_3acolsatcompiletime_2c_20matrixtype_3a_3acolsatcompiletime_20_3e',['Matrix&lt; Scalar, MatrixType::ColsAtCompileTime, MatrixType::ColsAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20matrixtype_3a_3arowsatcompiletime_2c_20minsize_20_3e',['Matrix&lt; Scalar, MatrixType::RowsAtCompileTime, MinSize &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20minsize_2c_201_20_3e',['Matrix&lt; Scalar, MinSize, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20rowsatcompiletime_2c_201_2c_20options_2c_20maxrowsatcompiletime_2c_201_20_3e',['Matrix&lt; Scalar, RowsAtCompileTime, 1, Options, MaxRowsAtCompileTime, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20rowsatcompiletime_2c_20rowsatcompiletime_2c_20matrixoptions_2c_20maxrowsatcompiletime_2c_20maxrowsatcompiletime_20_3e',['Matrix&lt; Scalar, RowsAtCompileTime, RowsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MaxRowsAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20size_2c_20size_2c_20colmajor_2c_20maxcolsatcompiletime_2c_20maxcolsatcompiletime_20_3e',['Matrix&lt; Scalar, Size, Size, ColMajor, MaxColsAtCompileTime, MaxColsAtCompileTime &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_3c_20scalar_2c_20sizeminusone_2c_201_2c_20options_20_26_7erowmajor_2c_20maxsizeminusone_2c_201_20_3e',['Matrix&lt; Scalar, SizeMinusOne, 1, Options &amp;~RowMajor, MaxSizeMinusOne, 1 &gt;',['../class_eigen_1_1_matrix.html',1,'Eigen']]],
  ['matrix_5fswap_5fimpl',['matrix_swap_impl',['../struct_eigen_1_1internal_1_1matrix__swap__impl.html',1,'Eigen::internal']]],
  ['matrix_5fswap_5fimpl_3c_20matrixtypea_2c_20matrixtypeb_2c_20true_20_3e',['matrix_swap_impl&lt; MatrixTypeA, MatrixTypeB, true &gt;',['../struct_eigen_1_1internal_1_1matrix__swap__impl_3_01_matrix_type_a_00_01_matrix_type_b_00_01true_01_4.html',1,'Eigen::internal']]],
  ['matrix_5ftype_5ftimes_5fscalar_5ftype',['matrix_type_times_scalar_type',['../struct_eigen_1_1internal_1_1matrix__type__times__scalar__type.html',1,'Eigen::internal']]],
  ['matrixbase',['MatrixBase',['../class_eigen_1_1_matrix_base.html',1,'Eigen']]],
  ['matrixbase_3c_20coeffbasedproduct_3c_20lhsnested_2c_20rhsnested_2c_20nestingflags_20_3e_20_3e',['MatrixBase&lt; CoeffBasedProduct&lt; LhsNested, RhsNested, NestingFlags &gt; &gt;',['../class_eigen_1_1_matrix_base.html',1,'Eigen']]],
  ['matrixbase_3c_20diagonalproduct_3c_20matrixtype_2c_20diagonaltype_2c_20productorder_20_3e_20_3e',['MatrixBase&lt; DiagonalProduct&lt; MatrixType, DiagonalType, ProductOrder &gt; &gt;',['../class_eigen_1_1_matrix_base.html',1,'Eigen']]],
  ['matrixbase_3c_20flagged_3c_20expressiontype_2c_20added_2c_20removed_20_3e_20_3e',['MatrixBase&lt; Flagged&lt; ExpressionType, Added, Removed &gt; &gt;',['../class_eigen_1_1_matrix_base.html',1,'Eigen']]],
  ['matrixbase_3c_20homogeneous_3c_20matrixtype_2c_20_5fdirection_20_3e_20_3e',['MatrixBase&lt; Homogeneous&lt; MatrixType, _Direction &gt; &gt;',['../class_eigen_1_1_matrix_base.html',1,'Eigen']]],
  ['matrixbase_3c_20matrixwrapper_3c_20expressiontype_20_3e_20_3e',['MatrixBase&lt; MatrixWrapper&lt; ExpressionType &gt; &gt;',['../class_eigen_1_1_matrix_base.html',1,'Eigen']]],
  ['matrixbase_3c_20minor_3c_20matrixtype_20_3e_20_3e',['MatrixBase&lt; Minor&lt; MatrixType &gt; &gt;',['../class_eigen_1_1_matrix_base.html',1,'Eigen']]],
  ['matrixexponential',['MatrixExponential',['../class_eigen_1_1_matrix_exponential.html',1,'Eigen']]],
  ['matrixexponentialreturnvalue',['MatrixExponentialReturnValue',['../struct_eigen_1_1_matrix_exponential_return_value.html',1,'Eigen']]],
  ['matrixfunction',['MatrixFunction',['../class_eigen_1_1_matrix_function.html',1,'Eigen']]],
  ['matrixfunction_3c_20matrixtype_2c_20atomictype_2c_200_20_3e',['MatrixFunction&lt; MatrixType, AtomicType, 0 &gt;',['../class_eigen_1_1_matrix_function_3_01_matrix_type_00_01_atomic_type_00_010_01_4.html',1,'Eigen']]],
  ['matrixfunction_3c_20matrixtype_2c_20atomictype_2c_201_20_3e',['MatrixFunction&lt; MatrixType, AtomicType, 1 &gt;',['../class_eigen_1_1_matrix_function_3_01_matrix_type_00_01_atomic_type_00_011_01_4.html',1,'Eigen']]],
  ['matrixfunctionatomic',['MatrixFunctionAtomic',['../class_eigen_1_1_matrix_function_atomic.html',1,'Eigen']]],
  ['matrixfunctionreturnvalue',['MatrixFunctionReturnValue',['../class_eigen_1_1_matrix_function_return_value.html',1,'Eigen']]],
  ['matrixlogarithmatomic',['MatrixLogarithmAtomic',['../class_eigen_1_1_matrix_logarithm_atomic.html',1,'Eigen']]],
  ['matrixlogarithmreturnvalue',['MatrixLogarithmReturnValue',['../class_eigen_1_1_matrix_logarithm_return_value.html',1,'Eigen']]],
  ['matrixmarketiterator',['MatrixMarketIterator',['../class_eigen_1_1_matrix_market_iterator.html',1,'Eigen']]],
  ['matrixpower',['MatrixPower',['../class_eigen_1_1_matrix_power.html',1,'Eigen']]],
  ['matrixpower_3c_20eigen_3a_3amap_20_3e',['MatrixPower&lt; Eigen::Map &gt;',['../class_eigen_1_1_matrix_power.html',1,'Eigen']]],
  ['matrixpoweratomic',['MatrixPowerAtomic',['../class_eigen_1_1_matrix_power_atomic.html',1,'Eigen']]],
  ['matrixpowerproduct',['MatrixPowerProduct',['../class_eigen_1_1_matrix_power_product.html',1,'Eigen']]],
  ['matrixpowerreturnvalue',['MatrixPowerReturnValue',['../class_eigen_1_1_matrix_power_return_value.html',1,'Eigen']]],
  ['matrixpowerretval',['MatrixPowerRetval',['../class_eigen_1_1_matrix_power_retval.html',1,'Eigen']]],
  ['matrixreplacement',['MatrixReplacement',['../class_matrix_replacement.html',1,'']]],
  ['matrixreplacement_5fproductreturntype',['MatrixReplacement_ProductReturnType',['../class_matrix_replacement___product_return_type.html',1,'']]],
  ['matrixsquareroot',['MatrixSquareRoot',['../class_eigen_1_1_matrix_square_root.html',1,'Eigen']]],
  ['matrixsquareroot_3c_20matrixtype_2c_200_20_3e',['MatrixSquareRoot&lt; MatrixType, 0 &gt;',['../class_eigen_1_1_matrix_square_root_3_01_matrix_type_00_010_01_4.html',1,'Eigen']]],
  ['matrixsquareroot_3c_20matrixtype_2c_201_20_3e',['MatrixSquareRoot&lt; MatrixType, 1 &gt;',['../class_eigen_1_1_matrix_square_root_3_01_matrix_type_00_011_01_4.html',1,'Eigen']]],
  ['matrixsquarerootquasitriangular',['MatrixSquareRootQuasiTriangular',['../class_eigen_1_1_matrix_square_root_quasi_triangular.html',1,'Eigen']]],
  ['matrixsquarerootreturnvalue',['MatrixSquareRootReturnValue',['../class_eigen_1_1_matrix_square_root_return_value.html',1,'Eigen']]],
  ['matrixsquareroottriangular',['MatrixSquareRootTriangular',['../class_eigen_1_1_matrix_square_root_triangular.html',1,'Eigen']]],
  ['matrixwrapper',['MatrixWrapper',['../class_eigen_1_1_matrix_wrapper.html',1,'Eigen']]],
  ['matrixxpr',['MatrixXpr',['../struct_eigen_1_1_matrix_xpr.html',1,'Eigen']]],
  ['max_5fcoeff_5fvisitor',['max_coeff_visitor',['../struct_eigen_1_1internal_1_1max__coeff__visitor.html',1,'Eigen::internal']]],
  ['member_5fredux',['member_redux',['../struct_eigen_1_1internal_1_1member__redux.html',1,'Eigen::internal']]],
  ['meta_5fsqrt',['meta_sqrt',['../class_eigen_1_1internal_1_1meta__sqrt.html',1,'Eigen::internal']]],
  ['meta_5fsqrt_3c_20y_2c_20infx_2c_20supx_2c_20true_20_3e',['meta_sqrt&lt; Y, InfX, SupX, true &gt;',['../class_eigen_1_1internal_1_1meta__sqrt_3_01_y_00_01_inf_x_00_01_sup_x_00_01true_01_4.html',1,'Eigen::internal']]],
  ['metisordering',['MetisOrdering',['../class_eigen_1_1_metis_ordering.html',1,'Eigen']]],
  ['mgh09_5ffunctor',['MGH09_functor',['../struct_m_g_h09__functor.html',1,'']]],
  ['mgh10_5ffunctor',['MGH10_functor',['../struct_m_g_h10__functor.html',1,'']]],
  ['mgh17_5ffunctor',['MGH17_functor',['../struct_m_g_h17__functor.html',1,'']]],
  ['min_5fcoeff_5fvisitor',['min_coeff_visitor',['../struct_eigen_1_1internal_1_1min__coeff__visitor.html',1,'Eigen::internal']]],
  ['minimizer_5fhelper1',['minimizer_helper1',['../struct_eigen_1_1internal_1_1minimizer__helper1.html',1,'Eigen::internal']]],
  ['minimizer_5fhelper2',['minimizer_helper2',['../struct_eigen_1_1internal_1_1minimizer__helper2.html',1,'Eigen::internal']]],
  ['minor',['Minor',['../class_eigen_1_1_minor.html',1,'Eigen']]],
  ['minres',['MINRES',['../class_eigen_1_1_m_i_n_r_e_s.html',1,'Eigen']]],
  ['misra1a_5ffunctor',['misra1a_functor',['../structmisra1a__functor.html',1,'']]],
  ['misra1d_5ffunctor',['misra1d_functor',['../structmisra1d__functor.html',1,'']]],
  ['mixed_5fperf_5fanalyzer',['Mixed_Perf_Analyzer',['../class_mixed___perf___analyzer.html',1,'']]],
  ['mkl_5fllt',['mkl_llt',['../struct_eigen_1_1internal_1_1mkl__llt.html',1,'Eigen::internal']]],
  ['mpreal',['mpreal',['../classmpfr_1_1mpreal.html',1,'mpfr']]],
  ['mtl4_5finterface',['mtl4_interface',['../classmtl4__interface.html',1,'']]],
  ['must_5fnest_5fby_5fvalue',['must_nest_by_value',['../struct_eigen_1_1internal_1_1must__nest__by__value.html',1,'Eigen::internal']]],
  ['my_5fexception',['my_exception',['../structmy__exception.html',1,'']]],
  ['my_5ffunctor',['my_functor',['../structmy__functor.html',1,'']]],
  ['myclassa',['MyClassA',['../class_my_class_a.html',1,'']]],
  ['myjacobipreconditioner',['MyJacobiPreconditioner',['../class_my_jacobi_preconditioner.html',1,'']]],
  ['mystruct',['MyStruct',['../struct_my_struct.html',1,'']]]
];
